UniversalFileSystem-Cli:
  UniversalFileSystem:
    FileSystems:
      
      File:
        UriRegexPattern: ^file:///.*$
        FileSystemFactoryClass: Basalt.UniversalFileSystem.File.FileFileSystemFactory
      
      S3:
        UriRegexPattern: ^s3://.*$
        FileSystemFactoryClass: Basalt.UniversalFileSystem.AwsS3.AwsS3FileSystemFactory
        Client:
          Credentials:
            Type: Basic
            AccessKey: test
            SecretKey: test
          Options:
            ServiceURL: http://localhost:4566
            ForcePathStyle: true
        Settings:
          CreateBucketIfNotExists: false
      
      AzureBlob:
        UriRegexPattern: ^abfss://.*$
        FileSystemFactoryClass: Basalt.UniversalFileSystem.AzureBlob.AzureBlobFileSystemFactory
        Client:
          ServiceUri: http://localhost:10000/account1
          Credentials:
            Type: StorageSharedKey
            AccountName: devstoreaccount1
            AccountKey: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
        Settings:
          CreateBlobContainerIfNotExists: false
          
      GoogleCloudStorage:
        UriRegexPattern: ^gs://ufs-it-gs/.*$
        FileSystemFactoryClass: Basalt.UniversalFileSystem.GoogleCloudStorage.GoogleCloudStorageFileSystemFactory
        Client:
          Credentials:
            Type: None
          Uri: http://localhost:4443/storage/v1/
        Settings:
          ProjectId: test-project-id
          CreateBucketIfNotExists: true
      
      Oss:
        UriRegexPattern: ^oss://.*$
        FileSystemFactoryClass: Basalt.UniversalFileSystem.AliyunOss.AliyunOssFileSystemFactory
        Client:
          Endpoint: http://127.0.0.1:8280
          Credentials:
            Type: Basic
            AccessKey: AccessKeyId
            SecretKey: AccessKeySecret
        Settings:
          CreateBucketIfNotExists: false

      Sftp:
        UriRegexPattern: ^sftp://localhost/sftp/ufs-it-sftp/.*$
        FileSystemFactoryClass: Basalt.UniversalFileSystem.Sftp.SftpFileSystemFactory
        Client:
          Host: localhost
          Port: 2222
          Username: demo
          Password: demo