name: build-and-test
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .net core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.428

      - name: Build solution - ${{ matrix.configuration }}
        uses: wen-yan/basalt-shared/.github/actions/dotnet-command@v1
        with:
          command: build
          configuration: ${{ matrix.configuration }}
          working-directory: ./src

      - name: Test solution - ${{ matrix.configuration }}
        uses: ./.github/actions/test-solution
        with:
          working-directory: ./src
          configuration: ${{ matrix.configuration }}
