name: build-and-test
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .net core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.428

      - name: Build solution - ${{ matrix.configuration }}
        uses: wen-yan/basalt-shared/.github/actions/dotnet-command@v1
        with:
          command: build
          configuration: ${{ matrix.configuration }}
          working-directory: ./src

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v2

      - name: Setup test environment
        run: |
          chmod +x ./localstack/startup.sh
          docker compose up --detach --build --wait
        working-directory: ./src/test-env

      - name: Run tests - ${{ matrix.configuration }}
        uses: wen-yan/basalt-shared/.github/actions/dotnet-command@v1
        with:
          command: test
          configuration: ${{ matrix.configuration }}
          working-directory: ./src

      - name: Stop test environment
        run: docker compose down
        working-directory: ./src/test-env
