name: pr

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  pr-check-branch-name:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check branch name
        uses: wen-yan/basalt-shared/.github/actions/check-pr-branch-name@v1

  pr-build:
    uses: ./.github/workflows/build-and-test.yaml

  pr-auto-approve:
    runs-on: ubuntu-22.04
    steps:
      - name: Auto approve if author is specific user
        uses: wen-yan/basalt-shared/.github/actions/auto-approve-pr@v1
        with:
          pr-auto-approve-bot-token: ${{ secrets.PR_AUTO_APPROVE_BOT_TOKEN }}
